import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import { Footer } from "@/components/layout/Footer"; 
import NavbarMain from "@/components/layout/NavbarMain";
import { AuthProvider } from "@/hooks/AuthContext";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  let user = null;
  let token = null
  try{
    const session = await auth?.api?.getSession({
      headers: await headers(),
    });
  
    user = session?.user;
  
    const tokenData = await auth?.api?.getToken({
      headers: await headers(),
    });
    token = tokenData?.token;
  }catch (error){
    console.log(error);
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider user={user} token={token}  >
          <NavbarMain />
          {children}
          <Footer /> 
        </AuthProvider>
      </body>
    </html>
  );
}
